### ISSUE TITLE
WIP Starter Pack issues

### ISSUE THREAD

**Issue by unxmaal** [sgidevnet/sgug-rse#111] opened 2020-07-05 13:46 UTC
After completing the README for 0.0.5, on a fresh system, the current SP for devs' rpms do not install as described.

`sudo rpm -Uvh noarch/*.rpm mips/*.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package libtool-2.4.6-32.sgugbeta.mips is already installed
        package libtool-ltdl-2.4.6-32.sgugbeta.mips is already installed
        package libtool-ltdl-devel-2.4.6-32.sgugbeta.mips is already installed`

Installing via sudo rpm -Uvh --reinstall noarch/*.rpm mips/*.rpm shows many conflicts between the installed package's files and its point-release update:

```
file /usr/sgug/bin/autoconf from install of autoconf-2.69-33.sgugbeta.noarch conflicts with file from package autoconf-2.69-32.sgugbeta.
noarch
```

**Comment by unxmaal** [comment] 2020-07-05 13:47
I resolved this on my other system by adding --force, then carefully removing the older version, but surely there's a better way.

**Comment by danielhams** [comment] 2020-07-05 13:57
Could you please try once again - but after untarring the SP files - remove the libtool related SRPM/RPMs.

It's possible that a "same version" crept in and that's the problem.

**Comment by unxmaal** [comment] 2020-07-05 14:14
I captured the list of packages affected: 

`autoconf-2.69-33.sgugbeta.noarch
bsdcat-3.3.3-1.sgugbeta.mips
bsdcpio-3.3.3-1.sgugbeta.mips
bsdtar-3.3.3-1.sgugbeta.mips
ddd-3.3.12-35.sgugbeta.mips
emacs-1:23.3-2.sgugbeta.mips
emacs-common-1:23.3-2.sgugbeta.mips
emacs-lucid-1:23.3-2.sgugbeta.mips
emacs-nox-1:23.3-2.sgugbeta.mips
fltk-1.3.5-4.sgugbeta.mips
fltk-devel-1.3.5-4.sgugbeta.mips
fltk-fluid-1.3.5-4.sgugbeta.mips
fltk-static-1.3.5-4.sgugbeta.mips
groff-1.22.4-22.sgugbeta.mips
groff-base-1.22.4-22.sgugbeta.mips
groff-doc-1.22.4-22.sgugbeta.noarch
groff-perl-1.22.4-22.sgugbeta.mips
groff-x11-1.22.4-22.sgugbeta.mips
libXpm-3.5.12-11.sgugbeta.mips
libXpm-devel-3.5.12-11.sgugbeta.mips
libarchive-3.3.3-1.sgugbeta.mips
libarchive-devel-3.3.3-1.sgugbeta.mips
make-1:4.3-15.sgugbeta.mips
make-1:4.3-15.sgugbeta.mips
make-devel-1:4.3-15.sgugbeta.mips
make-devel-1:4.3-15.sgugbeta.mips
rpm-4.15.0-11.sgugbeta.mips
tk-1:8.6.9.1-2.sgugbeta.mips
tk-devel-1:8.6.9.1-2.sgugbeta.mips
vim-X11-2:8.1.2102-3.sgugbeta.mips
vim-common-2:8.1.2102-3.sgugbeta.mips
vim-enhanced-2:8.1.2102-3.sgugbeta.mips
vim-minimal-2:8.1.2102-3.sgugbeta.mips`

**Comment by danielhams** [comment] 2020-07-05 14:19
@unxmaal - thanks, but that list isn't helpful - nor is telling people to use `--force` or `--reinstall`.

Did you try my suggestion?

Repeated for clarity:
* untar the sp SRPM/RPMs
* remove any libtool related ones, they are a duplicate of an already installed version
* follow the existing instructions and use `rpm -Uvh noarch/*.rpm mips/*.rpm`

**Comment by unxmaal** [comment] 2020-07-05 14:26
Confirmed: removing the libtool rpms fixed it. (Though I'm not sure how?)

**Comment by danielhams** [comment] 2020-07-05 14:27
Thank you for reporting this, and for confirming what needs to be done to fix it properly (remove the libtool RPMs from the sp).

I'll tweak the sp tarballs and re-upload em.

**Comment by danielhams** [comment] 2020-07-05 14:53
RPM tarball re-uploaded without the libtool duplicates in there. SRPM tarball didn't have it in.

**Comment by danielhams** [comment] 2020-08-18 17:26
0.0.6 is out, we'll need a new set of problems and wip packages :-)

**Closed by danielhams** 2020-08-18 17:26 UTC
